### Đăng ký
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "tesuser@example.com",
  "password": "123456",
  "fullname": "Nguyen Van A",
  "address": "Hanoi, Vietnam"
}

### Đăng nhập
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "tesuser@example.com",
  "password": "123456"
}
### CRUD Genre
### - Create
POST http://localhost:8080/admin/genre
Content-Type: application/json

{
  "genre": "Cartoon"
}
### - Read Genre
GET http://localhost:8080/admin/genre
### - Update Genre
PUT http://localhost:8080/admin/genre/11 
Content-Type: application/json

{
  "genre": "Animated Cartoon"
}
### - Delete Genre
DELETE http://localhost:8080/admin/genre/12
